CREATE TABLE PartFinder.Storefront
(
	StoreID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	StoreName NVARCHAR(64) NOT NULL,
	StoreAddress NVARCHAR(128) NOT NULL,
	ZipCode INT NOT NULL,
	CityID INT NOT NULL FOREIGN KEY REFERENCES PartFinder.Cities(CityID)

	UNIQUE(StoreAddress, ZipCode)
);